import * as functions from "./files/functions.js";

import "../scss/style.scss";
import spoller from "./files/spoller.js";
import slider from "./files/slider.js";
import burger from "./files/burger.js";
import search from "./files/search.js";
import basket from "./files/basket.js";
import modal from "./files/modal.js";
import { rangeSlider, triggerPassword } from "./files/form.js";
import tab from "./files/tab.js";
import { productCounter, productLike, productSize } from "./files/product.js";
import cookie from "./files/cookie.js";
import { filtersToggle } from "./files/filtersToggle.js";
import fancy from "./files/fancy.js";
import copy from "./files/copy.js";
import map from "./files/map.js";
import anchor from "./files/anchor.js";
import discountNumber from "./files/discountNumber.js";
import prevBtn from "./files/prevBtn.js";
import mask from "./files/mask.js";
import email from "./files/email.js";
import profile from "./files/profile.js";

functions.mediaAdaptive();
spoller();
slider();
burger();
search();
basket();
modal();
triggerPassword();
tab();
productSize();
productLike();
cookie();
rangeSlider();
filtersToggle();
fancy();
copy();
productCounter();
map();
anchor();
discountNumber();
prevBtn();
mask();
email();
profile();